input_file: "D:\\input.mfi"
output_dir: "C:\\output"
block_size: 1000000 # number of sectors per read. One sector is 512b 
work_size: 128
words_min: 10 # minimum number of words detected in a sector
words_max: 15 # maximum number of words detected in a sector
keywords: [""] # list of keywords to search for
# https://bitcoin.stackexchange.com/questions/41447/filesystem-is-corrupt-how-to-find-wallet-dat/41450#41450
signatures: 
    - [0x62, 0x31, 0x05, 0x00, 0x09, 0x00, 0x00, 0x00] # berkley db
    - [0x00, 0x01, 0x07, 0x6b, 0x65, 0x79, 0x6d, 0x65, 0x74, 0x61] # keymeta
    - [0x00, 0x01, 0x0a, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x6b, 0x65, 0x79] # defaultkey
    - [0x00, 0x01, 0x0a, 0x6d, 0x69, 0x6e, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e] # minversion
    - [0x00, 0x01, 0x09, 0x62, 0x65, 0x73, 0x74, 0x62, 0x6c, 0x6f, 0x63, 0x6b] # bestblock
    - [0x00, 0x01, 0x03, 0x61, 0x63, 0x63] # acc
    - [0x00, 0x01, 0x03, 0x6b, 0x65, 0x79] # key
    - [0x00, 0x01, 0x04, 0x63, 0x6b, 0x65, 0x79] # ckey
    - [0x00, 0x01, 0x04, 0x6d, 0x6b, 0x65, 0x79] # (mkey) (Only in encrypted wallets) 
    - [0x00, 0x01, 0x04, 0x6e, 0x61, 0x6d, 0x65] # name
    - [0x00, 0x01, 0x07, 0x70, 0x75, 0x72, 0x70, 0x6f, 0x73, 0x65] # purpose
min_words: 2 # filter by minimum number of words detected in a sector
match_all: false # if true, all keywords must be present in a sector to be considered, any otherwise
use_gpu: true # use GPU for processing